### ISSUE TITLE
Changing mechanism how fonts are installed 

### ISSUE THREAD

**Issue by Angxddeep** [k-mktr/fedora-things-to-do#4]
So the current way installs fonts under .fonts that is inside users home folder which works but isn't recommended nowadays by the Xdg-team they recommend fonts to install under .local/share/fonts/, honestly i don't even care but its better if we use the recommended way bcz there will some DE or app that will only use the new recommended way. I was earlier thinking about making a pull request but its your projects so i just wanted you to know about. :)

**Comment by k-mktr** [comment]
Thanks for pointing this out. I've checked the recommendation and will update the install directory for additional fonts tomorrow.

Also, thanks for your contribution and pull request. There are a few issues I will address a bit later.

**Comment by k-mktr** [comment]
Fonts directory changed. Issue resolved
